language: java
os:
  - linux
#  - osx
#  - windows

env:
  - DOCKER_COMPOSE_VERSION=1.21.2
jdk:
  - openjdk11

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"

script:
  - mvn install test verify -B -DskipDockerTests=true -P test-coverage,reportCoverage
  - mvn -pl coverage-reporter exec:java@report -P test-coverage

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x frontend/scripts/deploy-npm.sh && sh frontend/scripts/deploy-npm.sh
    on:
      tags: true
  - provider: script
    script: bash frontend/scripts/deploy-heroku-docker.sh conquery-dev
    on:
      branch: develop
  - provider: script
    script: bash frontend/scripts/deploy-heroku-docker.sh conquery
    on:
      branch: master
